apiVersion: v1
kind: Service
metadata:
  name: latex-compiler-service
spec:
  selector:
    app: latex-compiler-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
  