apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: easycv-app-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort # NodePort in local, LoadBalancer on cloud

