apiVersion: v1
kind: Service
metadata:
  name: easycv-service
spec:
  selector:
    app: easycv-app-deployment
  ports:
    - name: python-app
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: latex-app
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP # LoadBalancer in cloud, NodePort in local